// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition",
    "title": "gopenapi",
    "version": "0.1.0"
  },
  "basePath": "/api/v2",
  "paths": {
    "/healthz": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK message",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    },
    "/passwords/generateRandom": {
      "get": {
        "description": "Returns a random password with a length between 0 and 500 !",
        "parameters": [
          {
            "maximum": 500,
            "type": "integer",
            "description": "The length of the requested string.",
            "name": "length",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the randomly generated password.",
            "schema": {
              "type": "object",
              "properties": {
                "password": {
                  "description": "Randomly generated string",
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Invalid length was provided."
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition",
    "title": "gopenapi",
    "version": "0.1.0"
  },
  "basePath": "/api/v2",
  "paths": {
    "/healthz": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK message",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    },
    "/passwords/generateRandom": {
      "get": {
        "description": "Returns a random password with a length between 0 and 500 !",
        "parameters": [
          {
            "maximum": 500,
            "minimum": 0,
            "type": "integer",
            "description": "The length of the requested string.",
            "name": "length",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the randomly generated password.",
            "schema": {
              "type": "object",
              "properties": {
                "password": {
                  "description": "Randomly generated string",
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Invalid length was provided."
          }
        }
      }
    }
  }
}`))
}
